### ISSUE TITLE
use in cluster server

### ISSUE THREAD

**Issue by behroozshafiabadi** [ORESoftware/live-mutex#11]
if i have a cluster sever where is the best place for creating and initialize client object ?
i think the only place is master and not workers
because of in worker listening tcp port become "in used port" if one cluster initialize its client

**Comment by ORESoftware** [comment]
yeah I would use it in the master server

however, if you use it in the workers, you can use the utils method

`lmUtils. conditionallyLaunchSocketServer({port,host})`

and it will only launch the mutex broker/server if it's not already live

**Comment by ORESoftware** [comment]
if you explain your use case, I can help more

**Comment by ORESoftware** [comment]
@behroozshafiabadi  will close unless you have more questions
