### ISSUE TITLE
Don't need semicolons

### ISSUE THREAD

**Issue by knoxcard** [ORESoftware/live-mutex#12]
@ORESoftware Just a reminder, with NodeJS/Javascript you do not need semicolons.  I made sure my entire platform went semicolon free a year ago, it's just wonderful.  Reduces the file size, code faster, code looks cleaner, also easier to remember not putting a semicolon rather than putting one.  

Just my two cents.  :-)

**Comment by ORESoftware** [comment]
@knoxcard thanks for your thoughts :) I find semi-colons to be useful, especially for metaprogramming. if you are doing code generation, semi-colons are very useful.

removing semi-colons is only useful for style - I don't think it saves time.

however, using semi-colons is technically better, see this nightmare:
https://stackoverflow.com/questions/47984041/why-is-js-interpreting-foo-as-reading-a-property-instead-of-an-array-decla/47984076

that is why you should use semi-colons :)
