### ISSUE TITLE
Add option for IPC?

### ISSUE THREAD

**Issue by Zentendo** [ORESoftware/live-mutex#14]
Can you add an option for Unix Domain Sockets / Windows IPC? I feel using TCP will introduce intolerable latency by TCP overhead when communicating between local processes.

**Comment by ORESoftware** [comment]
not a bad idea, what do you think the performance difference is?

It turns out doing IPC between processes that don't have a parent/child relationship is kind of a pain, I have tried before - although I am not sure I have used Unix Domain Sockets before. Do you need Windows support or is UDS enough?

The big win for this library is that there is no polling needed - that's where the big performance gains are, not necessary that TCP is faster than filesystem I/O or pure IPC etc.

**Comment by ORESoftware** [comment]
So here is the only thing in the way of implementing this on MacOS:

connect ENOTSOCK /tmp/unix.sock

I need to find a way to create a "socket file" on the filesystem, otherwise I get the above error when calling

`net.createConnection(SOCKETFILE)`

**Comment by ORESoftware** [comment]
I left a comment on that gist in the link above - IPC like that will only work for one client connected to the server.

**Comment by ORESoftware** [comment]
@Zentendo I think I know what you were talking about now. On Linux there appears to be a delay for TCP requests going through localhost - it's called ACK delay or something like that.

See this:
https://github.com/nodejs/node/issues/21091

and this:
https://askubuntu.com/questions/1043028/changing-tcp-ack-delay

what Linux flavor are you using? We might be able to change the setting and you will see a lot better performance out of this library.

The difference in performance is night and day really. My MacOS machine does not have this delay and just blazes and my Linux machine (Ubuntu) has the delay and really is dog slow, like 100x slower.

**Comment by ORESoftware** [comment]
@Zentendo  if you install the latest version, TCP has been tuned to be much more performant on Linux. And it's only going to keep getting faster. There is a lot more TCP tuning to be done yet.

npm install live-mutex@0.0.10047

**Comment by ORESoftware** [comment]
@Zentendo  Unix Domain Sockets were implemented in version + live-mutex@0.0.10048

see the README on how to use.

thanks for heads up on that, I finally got UDS to work, I had doubts if they could be implemented using the same exact interface as TCP, but they can.
