### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by hkjeffchan** [ORESoftware/live-mutex#15]
Thanks for this great library!

1) [live-mutex client] recommends you attach a process.on('error') event handler
How to do so after lmUtils.conditionallyLaunchSocketServerp

2) How to reference the broker after lmUtils.conditionallyLaunchSocketServerp? The return promise is broker?

3) any possible way to shutdown the broker? need this to end the mocha test

4) what is the difference of the following?
launchSocketServer (error if another process already launch the server?)
conditionallyLaunchSocketServer (no error if another process already launch the server?)
launchBrokerInChildProcess (what exactly does child process mean here? another node process? when to use this?)

5) suppose we have 4 processes (A, B, C, D) and A is holding the broker. If A crashes, where should we create the broker again?

**Comment by ORESoftware** [comment]
Hey @hkjeffchan sure thing- 

1.   just use:

```js
process.on('error', function(e){
    console.error(e);
});
```
and

```js
process.on('warning', function(w){
    console.error(w);
});
```

Actually, live-mutex will only emit a `warning`, not an `error`, so I will update the codebase to reflect that.

2. How to reference the broker - use this:

```js
lmUtils.conditionallyLaunchSocketServerp(opts).then(b => {
   // b is the broker instance
});
```

3. to shutdown the broker just use:

```js
new Broker().close(function(err){});
```

4. `launchSocketServer` will always try to create a new broker, `conditionallyLaunchSocketServer` is just for convenience - it will check if a broker is already listen on that host/port.

5. I would try to launch the broker in a process that is only running the `live-mutex` code -that way it shouldn't crash - if you have your own code in their also running, it could crash. 


I updated the code, so update your version with -

```npm install -S live-mutex@latest```

**Comment by ORESoftware** [comment]
try: `live-mutex@0.0.10036`
