### ISSUE TITLE
Suggestion: Consider to use winston to support log level

### ISSUE THREAD

**Issue by hkjeffchan** [ORESoftware/live-mutex#18]
So that ppl can disable the info logging easily

Really want to get rib of this... :)
[live-mutex client info] the lock timeout is: 3500

**Comment by ORESoftware** [comment]
sounds like a good idea. the way this will work:

```js
const b = new Broker();
b.emitter.on('warning', function(){
   winston.log(...arguments);
});
```

```js
const c = new Client();
c.emitter.on('warning', function(){
   winston.log(...arguments);
});
```

that way you can control what logging function you use. this is already implemented, just have to polish it up.

**Comment by ORESoftware** [comment]
You can use the event emitters for logging, please use this new version:

`+ live-mutex@0.0.10044`

As I mentioned, use the event emitters for logging. You should always listen for `'warning'` events.
For added information, listen for `'info'` events as well.
