### ISSUE TITLE
version on npm is too old, could you please publish latest version on npm

### ISSUE THREAD

**Issue by mroed** [ORESoftware/live-mutex#3]
using uws 0.12.0 which is unavailable (should use 8.14.0 as you do in master bransh)

**Comment by ORESoftware** [comment]
ah thanks, will publish new version, just be aware that it's not working on MacOS currently.

**Comment by ORESoftware** [comment]
Published, all tests passing, thanks

https://www.npmjs.com/package/live-mutex

**Comment by ORESoftware** [comment]
the uws library that live-mutex uses is causing some problems, so I am going to move this lib from websockets to pure TCP in the next few days

**Comment by ORESoftware** [comment]
@mroed if you are curious, I changed the implementation from using uws to Node.js core TCP. It's not quite as fast, but more robust. uws was breaking on MacOS.  README is updated to reflect changes. Let me know if it works for you. You can see test/speed for examples.
