### ISSUE TITLE
Confusing warning message

### ISSUE THREAD

**Issue by jwhenshaw** [ORESoftware/live-mutex#43]
`{"i":969,"l":true,"exports":{}}` is being emitted and logged from the live-mutex client and I'm struggling to understand what this corresponds to.

It specifically seems to be emitted when the mutex is under high load or is unable to reach the broker due to a port not being accessable.

I've had a dig in the source code but still haven't found a source/reason for it being emitted.

Could you provide some insight, please?

Version: `0.1.1054`

**Comment by jwhenshaw** [comment]
Closing as it was my incompetence around logging.

**Comment by ORESoftware** [comment]
np, yeah when creating libraries sometimes a stray logging statement stays in there
