### ISSUE TITLE
error in "npm i live-mutex"

### ISSUE THREAD

**Issue by varad11** [ORESoftware/live-mutex#45]
Getting following error on windows 10 after I run "npm i live-mutex".

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! live-mutex@0.1.1054 postinstall: `./assets/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the live-mutex@0.1.1054 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GS-1567\AppData\Roaming\npm-cache\_logs\2018-11-12T10_08_06_121Z-debug.log

**Comment by ORESoftware** [comment]
sorry, doesn't work on windows yet :(

https://github.com/ORESoftware/live-mutex#disclaimer

if you are interested in getting in getting to work on windows, it shouldn't be that hard, lmk
