### ISSUE TITLE
Docker image base from node:alpine 

### ISSUE THREAD

**Issue by scalebig** [ORESoftware/live-mutex#56]
First - Thanks creating this package! We are using as part of a lightweight session mgr with locking support for an LMS.

Just a heads-up, the `postinstall.sh` blows up when bash isn't available. I am going to add bash via `apk add bash` for now. Just adds a bit more bloat when trying to keep images small with Alpine. If I get a moment I can take a stab making the script ash compliant also - and use  /bin/sh in the shell directive.

**Comment by ORESoftware** [comment]
ah thanks, yeah I can just use sh instead of bash, not a bad call

**Comment by ORESoftware** [comment]
by the way, just as a survey question - people tend to use this library in lieu of Redis/Redlock for a variety of reasons - just curious what informed your decision to use this lib?

**Comment by scalebig** [comment]
(this is probably a long winded answer that is specific to our needs...) Our ed-tech product still relegates some functionality to a legacy PHP LMS called Moodle on the backend. Its session manager relied on long-lived TCP connections with memcache or redis (and the existing redis session mgr implementation was half-backed & unusable) For whatever reason, PHP-FPM processes would drop the connections to our memcache server and bounce our users off in the middle of a quiz <not happy students>.  Moodle's session mgr pattern relies on blocking writes during reads (its just ugly). So

**Comment by scalebig** [comment]
While there is some overhead in start/stop a TCP connection for HTTP, we are able to pushed through 1200 updates or reads per second - plenty based on our load patterns. The "connected only when needed" approach eliminates any broken TCP connection issues that we were seeing. To be fair, we run everything in a Kubernetes cluster and container instances may get bounced. There was something in our architecture that legacy code (that expects "server hugging" infrastructure) wasn't prepared for.

**Comment by scalebig** [comment]
Ha - I never really answered "why this lib". I wanted it to be HTTP based, lightweight and easy to add hooks via nodejs. I didn't want to run yet another container for redis and then a wrapper around that... It was a days work using node-cache, live-mutex and expressjs packages. (oh and a histogram package to track some #s)

**Comment by ORESoftware** [comment]
nice that is cool - so you're just requesting to use alpine with the Docker image instead of `FROM node:11` or `FROM node:12` are you using  `oresoftware/live-mutex-broker` as a base image or something?

**Comment by ORESoftware** [comment]
well try it now, I updated to alpine, so it's:

```bash
docker run -p 6970:6970 -it oresoftware/live-mutex-broker:0.1.1060
```

the latest tag and 0.1.1060 should be the same but to force a pull probably good to use the version number

**Comment by ORESoftware** [comment]
At some point I was implementing reader-writer locks patterns with this, if you need something like that lmk, not sure if you do.

**Comment by tiggerite** [comment]
I would be interested in a readers writer lock, especially one that could be upgraded and downgraded. I’ve looked at the code for the clients you’ve created and can kind of understand (maybe not the readers being 1 using the writeKey though?)

**Comment by ORESoftware** [comment]
yeah I was working on the readers-writers lock, that's not finished yet, but might take another look at it

**Comment by tiggerite** [comment]
Yes sure, it's https://github.com/ORESoftware/live-mutex/blob/dev/src/rw-client.ts#L211

**Comment by ORESoftware** [comment]
@scalebig Hi Tim, if you are still using live-mutex I recommend upgrading to 0.2.0...there was a memory-leak in 0.1.x... also I deleted some docker images on docker hub without thinking and realized that I deleted all that were below 0.2.0, so a upgrade will be necessary.

**Comment by ORESoftware** [comment]
still using in prod? how's it goin? :)

**Comment by tiggerite** [comment]
I never used this in prod, and unfortunately moved away from that project now, had to use a simple read-write lock only instead and a singleton pattern. I'd have much preferred to use this though
