### ISSUE TITLE
Broker: Memory leak when sockets never disconnect

### ISSUE THREAD

**Issue by m-lawliet** [ORESoftware/live-mutex#68]
**Describe the bug**

This map:

> https://github.com/ORESoftware/live-mutex/blob/3f5341b42c6ebd2bfea20a377a6e27c7f27ac8cc/src/broker.ts#L567

is cleaned only on socket disconnect, end or error events.
If a socket is never closed, that map grows indefinitely.
This could happen for example when using Unix Domain Sockets in long living applications, when there is no reason to disconnect clients from broker, causing massive memory leaks over time.

I noted that Broker never actively uses "wsToUUIDs" map besides value initialization, so I don't get the point of having it at all.

I have temporarily patched my application commenting the line that populates the map:

> https://github.com/ORESoftware/live-mutex/blob/3f5341b42c6ebd2bfea20a377a6e27c7f27ac8cc/src/broker.ts#L1119

and runned my personal tests after that, with positive outcome.
This seem to confirm that "wsToUUIDs" map is not really useful at this stage. 

**To Reproduce**
1. Set up a Broker using a Unix Domain Socket
2. Set up a Client using a Unix Domain Socket
3. Launch a NodeJS application that performs lots of locks and unlocks (using flag --inspect)
4. Inspect Memory Heap usage evolution in time using Chrome tools (connect to ws exposed by NodeJS).
5. Note that "wsToUUIDs" map is growing in size and its values are never collected by V8 Garbage Collector 

**Expected behavior**
Please consider either removing that Map from code or implementing a better strategy for cleaning it up, to avoid Memory Leaks on applications using clients that never close connections.

**Comment by m-lawliet** [comment]
Thanks for patching!

I didn't mean that "wsToUUIDs" map isn't used at all, but that it has no real purpose.
You never do something like this in the code:

```ES6
const value = this.wsToUUIDs.get(ws)[uuid];
// Do something with value
```
All you do is pushing objects into a map and then cleaning it up without further elaborations, which will be something like:
```ES6
{
'0a0e6fa3-b384-4295-9c7e-6163a8019e95': true,
'0a2e9211-4ba2-4050-989e-e4482edf7c80': true,
'0a4b4ca3-c392-4d2e-96ed-a0edcc8c080f': true,
...
}
```
What does "true" means?
Could those values be anything than true? Does it really matter that a specific UUID has a value "true"? Does other parts of code really care?
It doesn't seem so.
Besides this, it is ok to maintain that Map as long as it is cleaned correcly.

Your patch mitigated the Memory Leak by a large factor, but some elements still remains on "wsToUUIDs" map without being collected.

I wrote a simple test application that created a certain amount of lock and unlocks and remains alive so that memory could be inspected after forcing Garbage Collector to run.
I've seen that a specific element of contained in the following map (just one element, not all of them) retains some data:

https://github.com/ORESoftware/live-mutex/blob/8698506ea71d6c6d0be50272277087302b9e76bb/src/broker.ts#L194

the data is stored in this attribute:

https://github.com/ORESoftware/live-mutex/blob/8698506ea71d6c6d0be50272277087302b9e76bb/src/broker.ts#L1256

with an internal structure similar to "wsToUUIDs" map.
I noted also "wsToUUIDs" map still had some elements and the size of the two maps were identical.
I checked and they both contain the same data (I mean, a copy, not a reference).

A further inspection showed that the leaking "UUIDs objects" were those where unlock was called using parameter "force" instead of a specific ID.
I relied on "force" option for convenience, but I suppose it is a better idea to save and pass correct ID.
Anyway, that map's values are not garbage collected correctly in such situation.
You should implement some code to clean it up.

**Comment by ORESoftware** [comment]
@m-lawliet btw, what technique/tool were you using to capture the memory for certain data structures at runtime? is it a chrome-based tool?

**Comment by m-lawliet** [comment]
I used V8's built-in inspector.
You just have to run your NodeJS process using `--inspect` flag, which exposes debug functionalities on a specific websocket.
Chrome is then used as a client for convenience, as it is well integrated (since NodeJS uses the same V8 engine developed originally for Chrome).
You can do some debug, memory inspection, etc by connecting to the exposed websocket visiting URL: [chrome://inspect/#devices](url)

You can get a clearer explanation on the official documentation:
[https://nodejs.org/de/docs/guides/debugging-getting-started/](url)

Here it is a more pratical guide:
[https://medium.com/tech-tajawal/memory-leaks-in-nodejs-quick-overview-988c23b24dba](url)

I recommend clicking on `Open dedicated DevTools for Node` instead of `inspect` on `Remote Target` section, since it also enables more advanced debugging that can be useful, with breakpoints, variable preview on current scope, etc.

**Comment by ORESoftware** [comment]
thanks for helping out with this
