### ISSUE TITLE
[feature] ttl per lock

### ISSUE THREAD

**Issue by marcj** [ORESoftware/live-mutex#73]
**Is your feature request related to a problem? Please describe.**

I have different locks with different TTL values. Currently, live-mutex only allows to set `ttl` on connection level, not on per lock level. Is there a reason for that?

**Describe the solution you'd like**

`this.client.acquire('my-id', {ttl: 5000})` means it lives max 5 seconds, if not extended (which isn't possible either at the moment afaik).

**Describe alternatives you've considered**
Alternative is to create a new connection for keys with different ttl. Not so practical.

**Additional context**

I'm writing a software with a lot of locks involved. Most of the time, the TTL differs heavily. Also most of the time, I have a long running commands that automatically extend/prolong the acquired lock, which isn't possible since the ttl is per connection. 
I'd really try out this wonderful project, but can't since those fundamentals are missing currently.

Also the generated `client.d.ts` is not correct.

For example:
`acquire(key: string, opts?: Partial<LMXClientLockOpts>): any;`

But `LMXClientLockOpts` is empty (LMXClientUnlockOpts as well)
```
export interface LMXClientLockOpts {
}
```

**Comment by marcj** [comment]
Oh, maybe I misunderstood the fundamental design of this lib. If the lock self-extends itself as long as it lives (connection is active and no unlock() called), then this ttl per lock is not necessary.

**Comment by ORESoftware** [comment]
Yeah, so it looks like this:

```typescript
  private lockInternal(key: string, opts: any, cb: LMClientLockCallBack) {
     // ...
    const ttl = opts.ttl || this.ttl;
     // ...
   }

```

you can pass ttl to the client contructor, and it will use that for all lock requests, until you pass ttl to a lock method which will override the class instance value. 

```typescript
lockp(k, {ttl:5000}, cb)
```
