### ISSUE TITLE
[feature] strict mode & API

### ISSUE THREAD

**Issue by marcj** [ORESoftware/live-mutex#74]
Currently, the documentation is only for non-strict mode in Typescript.

For example

```
client.ensure(err => {
   client.lock('<key>', (err, unlock) => {
       unlock(err => {  // unlock is a convenience function, bound to the correct key + request uuid

       });
   });
});
```

results in

![Screenshot 2019-08-31 at 17 00 34](https://user-images.githubusercontent.com/450980/64065695-dd8c1900-cc10-11e9-864e-04311bff6972.png)

## API

Also I have to say the API is not very good. A lot of `any` and a lot of methods that appear to do the same, yet most common use cases require own wrapper around the `Client` class. The API of `Client` is:

```
    requestLockInfo(key: string, opts?: any, cb?: EVCb<any>): void;
    lockp(key: string, opts?: Partial<LMXClientLockOpts>): Promise<LMLockSuccessData>;
    unlockp(key: string, opts?: Partial<LMXClientUnlockOpts>): Promise<LMUnlockSuccessData>;
    acquire(key: string, opts?: Partial<LMXClientLockOpts>): any;
    release(key: string, opts?: Partial<LMXClientUnlockOpts>): any;
    acquireLock(key: string, opts?: Partial<LMXClientLockOpts>): any;
    releaseLock(key: string, opts?: Partial<LMXClientUnlockOpts>): any;
    run(fn: LMLockSuccessData): Promise<unknown>;
    runUnlock(fn: LMLockSuccessData): Promise<any>;
    execUnlock(fn: LMLockSuccessData): Promise<any>;
    protected cleanUp(uuid: string): void;
    protected fireUnlockCallbackWithError(cb: LMClientUnlockCallBack, err: LMXClientUnlockException): void;
    protected fireLockCallbackWithError(cb: LMClientLockCallBack, err: LMXClientLockException): void;
    protected fireCallbackWithError(cb: EVCb<any>, err: LMXClientException): void;
    ls(cb: EVCb<any>): void;
    ls(opts: any, cb?: EVCb<any>): void;
    parseLockOpts(key: string, opts: any, cb?: any): [string, any, LMClientLockCallBack];
    parseUnlockOpts(key: string, opts?: any, cb?: any): [string, any, LMClientUnlockCallBack];
    _simulateVersionMismatch(): void;
    _invokeBrokerSideEndCall(): void;
    _invokeBrokerSideDestroyCall(): void;
    _makeClientSideError(): void;
    lock(key: string, cb: LMClientLockCallBack): void;
    lock(key: string, opts: any, cb: LMClientLockCallBack): void;
    on(): any;
    once(): any;
    private lockInternal;
    noop(err?: any): void;
    getPort(): number;
    getHost(): string;
    unlock(key: string): void;
    unlock(key: string, opts: any): void;
    unlock(key: string, opts: any, cb: LMClientUnlockCallBack): void;
```

With a lot of `any`, which is not best practise. I also don't know what to use to acquire a lock, there are multiple plausible definitions:

```
lockp(key: string, opts?: Partial<LMXClientLockOpts>): Promise<LMLockSuccessData>;
acquire(key: string, opts?: Partial<LMXClientLockOpts>): any;
acquireLock(key: string, opts?: Partial<LMXClientLockOpts>): any;
lock(key: string, cb: LMClientLockCallBack): void;
```

Only one appears to work with `await`, but I wonder why define an additional method for Promise result type? `lock` could do both, accept a cb and return a Promise. I also don't know what to use now, `lock` or `acquire`?
Same with release/unlock. Since there's no docblock above the methods, it's not very clear what methods to use.

## common use-case

I actually find an API like that more valuable:

```
const lock = await this.client.lock('key');
try {
    //do stuff
} finally {
    lock.release();
}
```

I actually also would find it useful to define a `timeout` for `.lock()` as I often have the use-case to actually check if a check is currently locked (either without locking it or unlock it immediately). Like so

```
//either build-in method
const exits: boolean = await this.client.isLocked('key');

//or the verbose way
function isLocked(key: string): boolean {
    try {
        const lock = await this.client.lockp('key', {timeout: 0})
        await lock.unlock();
        return true;
    } catch (error) {
        return false;
    }
}
```

**Comment by ORESoftware** [comment]
Sure when I first wrote this I was still relatively new to TS, I will improve the typings, thanks for the suggestions

**Comment by ORESoftware** [comment]
@marcj  while I work to get this to compile in --strict mode, you can use this compile option to get your project to compile:

```js
{
  "compilerOptions": {
    "skipLibCheck": true,   // here
  }
}
```

**Comment by ORESoftware** [comment]
Ok I made some changes, deprecated some methods, the dupe methods lockp and unlockp are deprecated, I agree those were confusing.

New version:

**live-mutex@0.2.0**


See this project:
https://github.com/ORESoftware/live-mutex-examples

It compiles with `tsc --strict`
