### ISSUE TITLE
EADDRINUSE: address already in use udsPath

### ISSUE THREAD

**Issue by OmgImAlexis** [ORESoftware/live-mutex#89]
I had a server started with `/tmp/lmx.sock` as the `udsPath` and it died unexpectedly(I killed it). When the server came back up it wouldn't reconnect.

Maybe add a way to have the server recover from this? You could have an option to enable this.
Catch `EADDRINUSE`, delete socket file, retry connection. If all good then no worries. Otherwise throw error like normal. That way permissions errors, etc. still get propagated but this doesn't have to be solved by the user.

```ts
Couldn't connect to broker. Error: listen EADDRINUSE: address already in use /tmp/lmx.sock
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1375:5)
    at /Users/xo/code/_/proxy/node_modules/live-mutex/dist/broker.js:306:31
    at new Promise (<anonymous>)
    at Broker.ensure.start (/Users/xo/code/_/proxy/node_modules/live-mutex/dist/broker.js:300:36)
    at handleServerConnecting (/Users/xo/code/_/proxy/app/index.js:239:31)
    at processTicksAndRejections (internal/process/task_queues.js:82:5) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '/tmp/lmx.sock',
  port: -1
}
```

**Comment by ORESoftware** [comment]
yep thanks will work on this

**Comment by ORESoftware** [comment]
so i assume the port will free up:
https://github.com/ORESoftware/live-mutex/blob/dev/src/broker.ts#L488

but maybe I need to manually delete the unix socket file path

**Comment by ORESoftware** [comment]
can't replicate this, but will keep an eye out for it

**Comment by OmgImAlexis** [comment]
touch the socket path and then try and start the application. It should remove the old broken socket and create a new one.

**Comment by ORESoftware** [comment]
ah yes, but i thought this was happening w the ports not just the socket?
