### ISSUE TITLE
API change recommendation

### ISSUE THREAD

**Issue by inf3rno** [ORESoftware/live-mutex#9]
You don't need 2 methods for lock with cb and promise. You can check whether the cb is present and if not, then return a promise. This is a little bit more error prone, but makes the api simpler. For example it is used here: https://github.com/jprichardson/node-fs-extra Another idea is to use utils.promisify if you keep the current api. https://nodejs.org/api/util.html#util_util_promisify_original And ofc it would be nice to see async-await examples with these promises...

**Comment by ORESoftware** [comment]
Thanks - I found that with static typing (typescript), it's cleaner to use two separate methods. I have another project where I had a conditional promise/callback, but I moved it to two separate methods. But I know what you mean. Let me know if the library works for you.

**Comment by ORESoftware** [comment]
I added a section in the docs describing usage with async/await

https://github.com/ORESoftware/live-mutex#to-use-with-asyncawait-it-simply-looks-like
