### ISSUE TITLE
Feature request: add option to disable logging

### ISSUE THREAD

**Issue by fabien** [ORESoftware/live-mutex#95]
Since any unhandled exceptions default to logging to the console, anytime a test/spec fails, a lot of 'garbage' is logged to the terminal.

I suggest adding the ability to disable logging, for example here:

https://github.com/ORESoftware/live-mutex/blob/cb7b296eca50bcd29da0b6e230b29fa736123fb9/src/utils.ts#L14

**Comment by ORESoftware** [comment]
cool that seems reasonable,  and env variable work for you?

**Comment by fabien** [comment]
Thanks! An environment variable would be perfect, too.

I tried adding my own handlers, but it doesn’t seem to prevent those uncaught errors from being logged verbosely.

Looking at the source-code, it seems that adding those handlers doesn’t affect those log calls.

**Comment by ORESoftware** [comment]
Can you drop a link in the code where you think the excess logging is happening?

**Comment by fabien** [comment]
I should mention that I’m running the broker inside the same process. I think this is the line:

https://github.com/ORESoftware/live-mutex/blob/cb7b296eca50bcd29da0b6e230b29fa736123fb9/src/broker.ts#L55

**Comment by ORESoftware** [comment]
ah, so are you running the broker on it's own, or you running your own code in the same process as the broker? Because if the broker process is on it's own and is experience an "uncaughtException", then that's not good. Can you show me an example of the error trace?

```js
process.on('uncaughtException', e => {
  // this shouldn't happen in the broker, if the broker is running without end user code
  log.error('Uncaught Exception event occurred in Broker process:', inspectError(e));
});
```

**Comment by fabien** [comment]
I'm running my code in the same process as my broker (or as I would say, I'm running the broker as part of my main process). Here's an example:

```
lmx broker error: Uncaught Exception event occurred in Broker process: TypeError: Cannot read property 'should' of undefined
```

**Comment by ORESoftware** [comment]
yeah, that exception is probably your code throwing the error. I can add the ability to remove the logs. another solution would be to run the broker just as a docker container, as shown in the readme.

**Comment by fabien** [comment]
Yes, it’s my code. More specifically, it’s whenever a test case fails. So errors are to be expected at times. Having such a verbose error trace is a bit annoying because it requires scrolling up a lot in the terminal (depending on the fixture or test-case). It is being logged in addition to the test’s error output itself, so it’s distracting.

In short, I prefer to keep the broker within my process (especially while testing).

So being able to turn it off would be extremely helpful.

**Comment by ORESoftware** [comment]
Yep makes sense

**Comment by fabien** [comment]
Hi, any chance of seeing this in an update soon? In a test-driven workflow, it's becoming extremely tedious to scroll way up and out of context whenever an assumption has not yet been met (errors out).

**Comment by ORESoftware** [comment]
hey will add it today

**Comment by ORESoftware** [comment]
ok please try it:  `live-mutex@0.2.25`

**Comment by ORESoftware** [comment]
@fabien  if it doesn't work for you please re-open, make sure to install the latest patch. thx!

**Comment by fabien** [comment]
@ORESoftware thanks! This seems to work - however, could you please publish it to npm?
